### ISSUE TITLE
Codage des détails d'une annonce

### ISSUE THREAD

**Issue by LukeCornaz** [Soreenn/Web_Project_CPNV#1]

**Comment by Soreenn** [comment]
- [x] Modèle d'annonce en carte Bootstrap
- [x] Redirection de l'utilisateur
- [x] Annonces crées automatiquement par rapport à la base de donnée
- [ ] Tags affichés
- [ ] Vue complète de l'annonce par simple clique dessus

Testé et confirmé par @LukeCornaz

![image](https://user-images.githubusercontent.com/35235150/110304069-70262900-7ffb-11eb-9b2a-753bb1692f7b.png)
